// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/common.proto

package message.common;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RetInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.RetInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *提示信息ID号
     * </pre>
     *
     * <code>int32 codeId = 1;</code>
     */
    int getCodeId();

    /**
     * <pre>
     *参数(占位符预留)
     * </pre>
     *
     * <code>repeated string datas = 2;</code>
     */
    java.util.List<java.lang.String>
        getDatasList();
    /**
     * <pre>
     *参数(占位符预留)
     * </pre>
     *
     * <code>repeated string datas = 2;</code>
     */
    int getDatasCount();
    /**
     * <pre>
     *参数(占位符预留)
     * </pre>
     *
     * <code>repeated string datas = 2;</code>
     */
    java.lang.String getDatas(int index);
    /**
     * <pre>
     *参数(占位符预留)
     * </pre>
     *
     * <code>repeated string datas = 2;</code>
     */
    com.google.protobuf.ByteString
        getDatasBytes(int index);
  }
  /**
   * <pre>
   *登录
   * </pre>
   *
   * Protobuf type {@code common.RetInfo}
   */
  public  static final class RetInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:common.RetInfo)
      RetInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RetInfo.newBuilder() to construct.
    private RetInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RetInfo() {
      codeId_ = 0;
      datas_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RetInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              codeId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                datas_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              datas_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          datas_ = datas_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.common.Common.internal_static_common_RetInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.common.Common.internal_static_common_RetInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.common.Common.RetInfo.class, message.common.Common.RetInfo.Builder.class);
    }

    private int bitField0_;
    public static final int CODEID_FIELD_NUMBER = 1;
    private int codeId_;
    /**
     * <pre>
     *提示信息ID号
     * </pre>
     *
     * <code>int32 codeId = 1;</code>
     */
    public int getCodeId() {
      return codeId_;
    }

    public static final int DATAS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList datas_;
    /**
     * <pre>
     *参数(占位符预留)
     * </pre>
     *
     * <code>repeated string datas = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDatasList() {
      return datas_;
    }
    /**
     * <pre>
     *参数(占位符预留)
     * </pre>
     *
     * <code>repeated string datas = 2;</code>
     */
    public int getDatasCount() {
      return datas_.size();
    }
    /**
     * <pre>
     *参数(占位符预留)
     * </pre>
     *
     * <code>repeated string datas = 2;</code>
     */
    public java.lang.String getDatas(int index) {
      return datas_.get(index);
    }
    /**
     * <pre>
     *参数(占位符预留)
     * </pre>
     *
     * <code>repeated string datas = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDatasBytes(int index) {
      return datas_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (codeId_ != 0) {
        output.writeInt32(1, codeId_);
      }
      for (int i = 0; i < datas_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, datas_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (codeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, codeId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < datas_.size(); i++) {
          dataSize += computeStringSizeNoTag(datas_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDatasList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.common.Common.RetInfo)) {
        return super.equals(obj);
      }
      message.common.Common.RetInfo other = (message.common.Common.RetInfo) obj;

      boolean result = true;
      result = result && (getCodeId()
          == other.getCodeId());
      result = result && getDatasList()
          .equals(other.getDatasList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODEID_FIELD_NUMBER;
      hash = (53 * hash) + getCodeId();
      if (getDatasCount() > 0) {
        hash = (37 * hash) + DATAS_FIELD_NUMBER;
        hash = (53 * hash) + getDatasList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.common.Common.RetInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.common.Common.RetInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.common.Common.RetInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.common.Common.RetInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.common.Common.RetInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.common.Common.RetInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.common.Common.RetInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.common.Common.RetInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.common.Common.RetInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static message.common.Common.RetInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.common.Common.RetInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.common.Common.RetInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.common.Common.RetInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *登录
     * </pre>
     *
     * Protobuf type {@code common.RetInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.RetInfo)
        message.common.Common.RetInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.common.Common.internal_static_common_RetInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.common.Common.internal_static_common_RetInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.common.Common.RetInfo.class, message.common.Common.RetInfo.Builder.class);
      }

      // Construct using message.common.Common.RetInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        codeId_ = 0;

        datas_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.common.Common.internal_static_common_RetInfo_descriptor;
      }

      public message.common.Common.RetInfo getDefaultInstanceForType() {
        return message.common.Common.RetInfo.getDefaultInstance();
      }

      public message.common.Common.RetInfo build() {
        message.common.Common.RetInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public message.common.Common.RetInfo buildPartial() {
        message.common.Common.RetInfo result = new message.common.Common.RetInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.codeId_ = codeId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          datas_ = datas_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.datas_ = datas_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.common.Common.RetInfo) {
          return mergeFrom((message.common.Common.RetInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.common.Common.RetInfo other) {
        if (other == message.common.Common.RetInfo.getDefaultInstance()) return this;
        if (other.getCodeId() != 0) {
          setCodeId(other.getCodeId());
        }
        if (!other.datas_.isEmpty()) {
          if (datas_.isEmpty()) {
            datas_ = other.datas_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDatasIsMutable();
            datas_.addAll(other.datas_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        message.common.Common.RetInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (message.common.Common.RetInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int codeId_ ;
      /**
       * <pre>
       *提示信息ID号
       * </pre>
       *
       * <code>int32 codeId = 1;</code>
       */
      public int getCodeId() {
        return codeId_;
      }
      /**
       * <pre>
       *提示信息ID号
       * </pre>
       *
       * <code>int32 codeId = 1;</code>
       */
      public Builder setCodeId(int value) {
        
        codeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *提示信息ID号
       * </pre>
       *
       * <code>int32 codeId = 1;</code>
       */
      public Builder clearCodeId() {
        
        codeId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList datas_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDatasIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          datas_ = new com.google.protobuf.LazyStringArrayList(datas_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       *参数(占位符预留)
       * </pre>
       *
       * <code>repeated string datas = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDatasList() {
        return datas_.getUnmodifiableView();
      }
      /**
       * <pre>
       *参数(占位符预留)
       * </pre>
       *
       * <code>repeated string datas = 2;</code>
       */
      public int getDatasCount() {
        return datas_.size();
      }
      /**
       * <pre>
       *参数(占位符预留)
       * </pre>
       *
       * <code>repeated string datas = 2;</code>
       */
      public java.lang.String getDatas(int index) {
        return datas_.get(index);
      }
      /**
       * <pre>
       *参数(占位符预留)
       * </pre>
       *
       * <code>repeated string datas = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDatasBytes(int index) {
        return datas_.getByteString(index);
      }
      /**
       * <pre>
       *参数(占位符预留)
       * </pre>
       *
       * <code>repeated string datas = 2;</code>
       */
      public Builder setDatas(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDatasIsMutable();
        datas_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *参数(占位符预留)
       * </pre>
       *
       * <code>repeated string datas = 2;</code>
       */
      public Builder addDatas(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDatasIsMutable();
        datas_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *参数(占位符预留)
       * </pre>
       *
       * <code>repeated string datas = 2;</code>
       */
      public Builder addAllDatas(
          java.lang.Iterable<java.lang.String> values) {
        ensureDatasIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, datas_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *参数(占位符预留)
       * </pre>
       *
       * <code>repeated string datas = 2;</code>
       */
      public Builder clearDatas() {
        datas_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *参数(占位符预留)
       * </pre>
       *
       * <code>repeated string datas = 2;</code>
       */
      public Builder addDatasBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDatasIsMutable();
        datas_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:common.RetInfo)
    }

    // @@protoc_insertion_point(class_scope:common.RetInfo)
    private static final message.common.Common.RetInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.common.Common.RetInfo();
    }

    public static message.common.Common.RetInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RetInfo>
        PARSER = new com.google.protobuf.AbstractParser<RetInfo>() {
      public RetInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RetInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RetInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RetInfo> getParserForType() {
      return PARSER;
    }

    public message.common.Common.RetInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ItemInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.ItemInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *道具表配置id
     * </pre>
     *
     * <code>int32 itemId = 1;</code>
     */
    int getItemId();

    /**
     * <pre>
     *拥有的数量
     * </pre>
     *
     * <code>int32 itemCount = 2;</code>
     */
    int getItemCount();
  }
  /**
   * Protobuf type {@code common.ItemInfo}
   */
  public  static final class ItemInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:common.ItemInfo)
      ItemInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ItemInfo.newBuilder() to construct.
    private ItemInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ItemInfo() {
      itemId_ = 0;
      itemCount_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ItemInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              itemId_ = input.readInt32();
              break;
            }
            case 16: {

              itemCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.common.Common.internal_static_common_ItemInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.common.Common.internal_static_common_ItemInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.common.Common.ItemInfo.class, message.common.Common.ItemInfo.Builder.class);
    }

    public static final int ITEMID_FIELD_NUMBER = 1;
    private int itemId_;
    /**
     * <pre>
     *道具表配置id
     * </pre>
     *
     * <code>int32 itemId = 1;</code>
     */
    public int getItemId() {
      return itemId_;
    }

    public static final int ITEMCOUNT_FIELD_NUMBER = 2;
    private int itemCount_;
    /**
     * <pre>
     *拥有的数量
     * </pre>
     *
     * <code>int32 itemCount = 2;</code>
     */
    public int getItemCount() {
      return itemCount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (itemId_ != 0) {
        output.writeInt32(1, itemId_);
      }
      if (itemCount_ != 0) {
        output.writeInt32(2, itemCount_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (itemId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, itemId_);
      }
      if (itemCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, itemCount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.common.Common.ItemInfo)) {
        return super.equals(obj);
      }
      message.common.Common.ItemInfo other = (message.common.Common.ItemInfo) obj;

      boolean result = true;
      result = result && (getItemId()
          == other.getItemId());
      result = result && (getItemCount()
          == other.getItemCount());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ITEMID_FIELD_NUMBER;
      hash = (53 * hash) + getItemId();
      hash = (37 * hash) + ITEMCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getItemCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.common.Common.ItemInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.common.Common.ItemInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.common.Common.ItemInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.common.Common.ItemInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.common.Common.ItemInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.common.Common.ItemInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.common.Common.ItemInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.common.Common.ItemInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.common.Common.ItemInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static message.common.Common.ItemInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.common.Common.ItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.common.Common.ItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.common.Common.ItemInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.ItemInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.ItemInfo)
        message.common.Common.ItemInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.common.Common.internal_static_common_ItemInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.common.Common.internal_static_common_ItemInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.common.Common.ItemInfo.class, message.common.Common.ItemInfo.Builder.class);
      }

      // Construct using message.common.Common.ItemInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        itemId_ = 0;

        itemCount_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.common.Common.internal_static_common_ItemInfo_descriptor;
      }

      public message.common.Common.ItemInfo getDefaultInstanceForType() {
        return message.common.Common.ItemInfo.getDefaultInstance();
      }

      public message.common.Common.ItemInfo build() {
        message.common.Common.ItemInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public message.common.Common.ItemInfo buildPartial() {
        message.common.Common.ItemInfo result = new message.common.Common.ItemInfo(this);
        result.itemId_ = itemId_;
        result.itemCount_ = itemCount_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.common.Common.ItemInfo) {
          return mergeFrom((message.common.Common.ItemInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.common.Common.ItemInfo other) {
        if (other == message.common.Common.ItemInfo.getDefaultInstance()) return this;
        if (other.getItemId() != 0) {
          setItemId(other.getItemId());
        }
        if (other.getItemCount() != 0) {
          setItemCount(other.getItemCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        message.common.Common.ItemInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (message.common.Common.ItemInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int itemId_ ;
      /**
       * <pre>
       *道具表配置id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       */
      public int getItemId() {
        return itemId_;
      }
      /**
       * <pre>
       *道具表配置id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       */
      public Builder setItemId(int value) {
        
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *道具表配置id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       */
      public Builder clearItemId() {
        
        itemId_ = 0;
        onChanged();
        return this;
      }

      private int itemCount_ ;
      /**
       * <pre>
       *拥有的数量
       * </pre>
       *
       * <code>int32 itemCount = 2;</code>
       */
      public int getItemCount() {
        return itemCount_;
      }
      /**
       * <pre>
       *拥有的数量
       * </pre>
       *
       * <code>int32 itemCount = 2;</code>
       */
      public Builder setItemCount(int value) {
        
        itemCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *拥有的数量
       * </pre>
       *
       * <code>int32 itemCount = 2;</code>
       */
      public Builder clearItemCount() {
        
        itemCount_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:common.ItemInfo)
    }

    // @@protoc_insertion_point(class_scope:common.ItemInfo)
    private static final message.common.Common.ItemInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.common.Common.ItemInfo();
    }

    public static message.common.Common.ItemInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ItemInfo>
        PARSER = new com.google.protobuf.AbstractParser<ItemInfo>() {
      public ItemInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ItemInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ItemInfo> getParserForType() {
      return PARSER;
    }

    public message.common.Common.ItemInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GoodsInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.GoodsInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *道具配置Id
     * </pre>
     *
     * <code>int32 tplId = 1;</code>
     */
    int getTplId();

    /**
     * <pre>
     *放入的格子
     * </pre>
     *
     * <code>int32 slot = 2;</code>
     */
    int getSlot();
  }
  /**
   * <pre>
   *道具信息
   * </pre>
   *
   * Protobuf type {@code common.GoodsInfo}
   */
  public  static final class GoodsInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:common.GoodsInfo)
      GoodsInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GoodsInfo.newBuilder() to construct.
    private GoodsInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GoodsInfo() {
      tplId_ = 0;
      slot_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GoodsInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              tplId_ = input.readInt32();
              break;
            }
            case 16: {

              slot_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.common.Common.internal_static_common_GoodsInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.common.Common.internal_static_common_GoodsInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.common.Common.GoodsInfo.class, message.common.Common.GoodsInfo.Builder.class);
    }

    public static final int TPLID_FIELD_NUMBER = 1;
    private int tplId_;
    /**
     * <pre>
     *道具配置Id
     * </pre>
     *
     * <code>int32 tplId = 1;</code>
     */
    public int getTplId() {
      return tplId_;
    }

    public static final int SLOT_FIELD_NUMBER = 2;
    private int slot_;
    /**
     * <pre>
     *放入的格子
     * </pre>
     *
     * <code>int32 slot = 2;</code>
     */
    public int getSlot() {
      return slot_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (tplId_ != 0) {
        output.writeInt32(1, tplId_);
      }
      if (slot_ != 0) {
        output.writeInt32(2, slot_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (tplId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, tplId_);
      }
      if (slot_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, slot_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.common.Common.GoodsInfo)) {
        return super.equals(obj);
      }
      message.common.Common.GoodsInfo other = (message.common.Common.GoodsInfo) obj;

      boolean result = true;
      result = result && (getTplId()
          == other.getTplId());
      result = result && (getSlot()
          == other.getSlot());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TPLID_FIELD_NUMBER;
      hash = (53 * hash) + getTplId();
      hash = (37 * hash) + SLOT_FIELD_NUMBER;
      hash = (53 * hash) + getSlot();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.common.Common.GoodsInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.common.Common.GoodsInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.common.Common.GoodsInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.common.Common.GoodsInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.common.Common.GoodsInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.common.Common.GoodsInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.common.Common.GoodsInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.common.Common.GoodsInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.common.Common.GoodsInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static message.common.Common.GoodsInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.common.Common.GoodsInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.common.Common.GoodsInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.common.Common.GoodsInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *道具信息
     * </pre>
     *
     * Protobuf type {@code common.GoodsInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.GoodsInfo)
        message.common.Common.GoodsInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.common.Common.internal_static_common_GoodsInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.common.Common.internal_static_common_GoodsInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.common.Common.GoodsInfo.class, message.common.Common.GoodsInfo.Builder.class);
      }

      // Construct using message.common.Common.GoodsInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        tplId_ = 0;

        slot_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.common.Common.internal_static_common_GoodsInfo_descriptor;
      }

      public message.common.Common.GoodsInfo getDefaultInstanceForType() {
        return message.common.Common.GoodsInfo.getDefaultInstance();
      }

      public message.common.Common.GoodsInfo build() {
        message.common.Common.GoodsInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public message.common.Common.GoodsInfo buildPartial() {
        message.common.Common.GoodsInfo result = new message.common.Common.GoodsInfo(this);
        result.tplId_ = tplId_;
        result.slot_ = slot_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.common.Common.GoodsInfo) {
          return mergeFrom((message.common.Common.GoodsInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.common.Common.GoodsInfo other) {
        if (other == message.common.Common.GoodsInfo.getDefaultInstance()) return this;
        if (other.getTplId() != 0) {
          setTplId(other.getTplId());
        }
        if (other.getSlot() != 0) {
          setSlot(other.getSlot());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        message.common.Common.GoodsInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (message.common.Common.GoodsInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int tplId_ ;
      /**
       * <pre>
       *道具配置Id
       * </pre>
       *
       * <code>int32 tplId = 1;</code>
       */
      public int getTplId() {
        return tplId_;
      }
      /**
       * <pre>
       *道具配置Id
       * </pre>
       *
       * <code>int32 tplId = 1;</code>
       */
      public Builder setTplId(int value) {
        
        tplId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *道具配置Id
       * </pre>
       *
       * <code>int32 tplId = 1;</code>
       */
      public Builder clearTplId() {
        
        tplId_ = 0;
        onChanged();
        return this;
      }

      private int slot_ ;
      /**
       * <pre>
       *放入的格子
       * </pre>
       *
       * <code>int32 slot = 2;</code>
       */
      public int getSlot() {
        return slot_;
      }
      /**
       * <pre>
       *放入的格子
       * </pre>
       *
       * <code>int32 slot = 2;</code>
       */
      public Builder setSlot(int value) {
        
        slot_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *放入的格子
       * </pre>
       *
       * <code>int32 slot = 2;</code>
       */
      public Builder clearSlot() {
        
        slot_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:common.GoodsInfo)
    }

    // @@protoc_insertion_point(class_scope:common.GoodsInfo)
    private static final message.common.Common.GoodsInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.common.Common.GoodsInfo();
    }

    public static message.common.Common.GoodsInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GoodsInfo>
        PARSER = new com.google.protobuf.AbstractParser<GoodsInfo>() {
      public GoodsInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GoodsInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GoodsInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GoodsInfo> getParserForType() {
      return PARSER;
    }

    public message.common.Common.GoodsInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ParentInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.ParentInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *父类关卡id
     * </pre>
     *
     * <code>int32 tplId = 1;</code>
     */
    int getTplId();

    /**
     * <pre>
     *三星奖励，1:可领奖  2:未完成  3:已领奖
     * </pre>
     *
     * <code>int32 state = 2;</code>
     */
    int getState();
  }
  /**
   * Protobuf type {@code common.ParentInfo}
   */
  public  static final class ParentInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:common.ParentInfo)
      ParentInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ParentInfo.newBuilder() to construct.
    private ParentInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParentInfo() {
      tplId_ = 0;
      state_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ParentInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              tplId_ = input.readInt32();
              break;
            }
            case 16: {

              state_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.common.Common.internal_static_common_ParentInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.common.Common.internal_static_common_ParentInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.common.Common.ParentInfo.class, message.common.Common.ParentInfo.Builder.class);
    }

    public static final int TPLID_FIELD_NUMBER = 1;
    private int tplId_;
    /**
     * <pre>
     *父类关卡id
     * </pre>
     *
     * <code>int32 tplId = 1;</code>
     */
    public int getTplId() {
      return tplId_;
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private int state_;
    /**
     * <pre>
     *三星奖励，1:可领奖  2:未完成  3:已领奖
     * </pre>
     *
     * <code>int32 state = 2;</code>
     */
    public int getState() {
      return state_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (tplId_ != 0) {
        output.writeInt32(1, tplId_);
      }
      if (state_ != 0) {
        output.writeInt32(2, state_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (tplId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, tplId_);
      }
      if (state_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, state_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.common.Common.ParentInfo)) {
        return super.equals(obj);
      }
      message.common.Common.ParentInfo other = (message.common.Common.ParentInfo) obj;

      boolean result = true;
      result = result && (getTplId()
          == other.getTplId());
      result = result && (getState()
          == other.getState());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TPLID_FIELD_NUMBER;
      hash = (53 * hash) + getTplId();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.common.Common.ParentInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.common.Common.ParentInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.common.Common.ParentInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.common.Common.ParentInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.common.Common.ParentInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.common.Common.ParentInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.common.Common.ParentInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.common.Common.ParentInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.common.Common.ParentInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static message.common.Common.ParentInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.common.Common.ParentInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.common.Common.ParentInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.common.Common.ParentInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.ParentInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.ParentInfo)
        message.common.Common.ParentInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.common.Common.internal_static_common_ParentInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.common.Common.internal_static_common_ParentInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.common.Common.ParentInfo.class, message.common.Common.ParentInfo.Builder.class);
      }

      // Construct using message.common.Common.ParentInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        tplId_ = 0;

        state_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.common.Common.internal_static_common_ParentInfo_descriptor;
      }

      public message.common.Common.ParentInfo getDefaultInstanceForType() {
        return message.common.Common.ParentInfo.getDefaultInstance();
      }

      public message.common.Common.ParentInfo build() {
        message.common.Common.ParentInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public message.common.Common.ParentInfo buildPartial() {
        message.common.Common.ParentInfo result = new message.common.Common.ParentInfo(this);
        result.tplId_ = tplId_;
        result.state_ = state_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.common.Common.ParentInfo) {
          return mergeFrom((message.common.Common.ParentInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.common.Common.ParentInfo other) {
        if (other == message.common.Common.ParentInfo.getDefaultInstance()) return this;
        if (other.getTplId() != 0) {
          setTplId(other.getTplId());
        }
        if (other.getState() != 0) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        message.common.Common.ParentInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (message.common.Common.ParentInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int tplId_ ;
      /**
       * <pre>
       *父类关卡id
       * </pre>
       *
       * <code>int32 tplId = 1;</code>
       */
      public int getTplId() {
        return tplId_;
      }
      /**
       * <pre>
       *父类关卡id
       * </pre>
       *
       * <code>int32 tplId = 1;</code>
       */
      public Builder setTplId(int value) {
        
        tplId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *父类关卡id
       * </pre>
       *
       * <code>int32 tplId = 1;</code>
       */
      public Builder clearTplId() {
        
        tplId_ = 0;
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <pre>
       *三星奖励，1:可领奖  2:未完成  3:已领奖
       * </pre>
       *
       * <code>int32 state = 2;</code>
       */
      public int getState() {
        return state_;
      }
      /**
       * <pre>
       *三星奖励，1:可领奖  2:未完成  3:已领奖
       * </pre>
       *
       * <code>int32 state = 2;</code>
       */
      public Builder setState(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *三星奖励，1:可领奖  2:未完成  3:已领奖
       * </pre>
       *
       * <code>int32 state = 2;</code>
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:common.ParentInfo)
    }

    // @@protoc_insertion_point(class_scope:common.ParentInfo)
    private static final message.common.Common.ParentInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.common.Common.ParentInfo();
    }

    public static message.common.Common.ParentInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParentInfo>
        PARSER = new com.google.protobuf.AbstractParser<ParentInfo>() {
      public ParentInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ParentInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ParentInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParentInfo> getParserForType() {
      return PARSER;
    }

    public message.common.Common.ParentInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_RetInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_RetInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_ItemInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_ItemInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_GoodsInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_GoodsInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_ParentInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_ParentInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023common/common.proto\022\006common\"(\n\007RetInfo" +
      "\022\016\n\006codeId\030\001 \001(\005\022\r\n\005datas\030\002 \003(\t\"-\n\010ItemI" +
      "nfo\022\016\n\006itemId\030\001 \001(\005\022\021\n\titemCount\030\002 \001(\005\"(" +
      "\n\tGoodsInfo\022\r\n\005tplId\030\001 \001(\005\022\014\n\004slot\030\002 \001(\005" +
      "\"*\n\nParentInfo\022\r\n\005tplId\030\001 \001(\005\022\r\n\005state\030\002" +
      " \001(\005B\030\n\016message.commonB\006Commonb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_common_RetInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_RetInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_RetInfo_descriptor,
        new java.lang.String[] { "CodeId", "Datas", });
    internal_static_common_ItemInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_ItemInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_ItemInfo_descriptor,
        new java.lang.String[] { "ItemId", "ItemCount", });
    internal_static_common_GoodsInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_common_GoodsInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_GoodsInfo_descriptor,
        new java.lang.String[] { "TplId", "Slot", });
    internal_static_common_ParentInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_common_ParentInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_ParentInfo_descriptor,
        new java.lang.String[] { "TplId", "State", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
