// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bag.proto

package message;

public final class Bag {
  private Bag() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SC_UpdateItemInfosOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bag.SC_UpdateItemInfos)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *道具信息 itemCount = 0 表示删除
     * </pre>
     *
     * <code>repeated .common.ItemInfo itemInfos = 1;</code>
     */
    java.util.List<message.common.Common.ItemInfo> 
        getItemInfosList();
    /**
     * <pre>
     *道具信息 itemCount = 0 表示删除
     * </pre>
     *
     * <code>repeated .common.ItemInfo itemInfos = 1;</code>
     */
    message.common.Common.ItemInfo getItemInfos(int index);
    /**
     * <pre>
     *道具信息 itemCount = 0 表示删除
     * </pre>
     *
     * <code>repeated .common.ItemInfo itemInfos = 1;</code>
     */
    int getItemInfosCount();
    /**
     * <pre>
     *道具信息 itemCount = 0 表示删除
     * </pre>
     *
     * <code>repeated .common.ItemInfo itemInfos = 1;</code>
     */
    java.util.List<? extends message.common.Common.ItemInfoOrBuilder> 
        getItemInfosOrBuilderList();
    /**
     * <pre>
     *道具信息 itemCount = 0 表示删除
     * </pre>
     *
     * <code>repeated .common.ItemInfo itemInfos = 1;</code>
     */
    message.common.Common.ItemInfoOrBuilder getItemInfosOrBuilder(
        int index);
  }
  /**
   * <pre>
   *服务器主动推送更新背包数据
   * </pre>
   *
   * Protobuf type {@code bag.SC_UpdateItemInfos}
   */
  public  static final class SC_UpdateItemInfos extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bag.SC_UpdateItemInfos)
      SC_UpdateItemInfosOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SC_UpdateItemInfos.newBuilder() to construct.
    private SC_UpdateItemInfos(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SC_UpdateItemInfos() {
      itemInfos_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SC_UpdateItemInfos(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                itemInfos_ = new java.util.ArrayList<message.common.Common.ItemInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              itemInfos_.add(
                  input.readMessage(message.common.Common.ItemInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          itemInfos_ = java.util.Collections.unmodifiableList(itemInfos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.Bag.internal_static_bag_SC_UpdateItemInfos_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.Bag.internal_static_bag_SC_UpdateItemInfos_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.Bag.SC_UpdateItemInfos.class, message.Bag.SC_UpdateItemInfos.Builder.class);
    }

    public static final int ITEMINFOS_FIELD_NUMBER = 1;
    private java.util.List<message.common.Common.ItemInfo> itemInfos_;
    /**
     * <pre>
     *道具信息 itemCount = 0 表示删除
     * </pre>
     *
     * <code>repeated .common.ItemInfo itemInfos = 1;</code>
     */
    public java.util.List<message.common.Common.ItemInfo> getItemInfosList() {
      return itemInfos_;
    }
    /**
     * <pre>
     *道具信息 itemCount = 0 表示删除
     * </pre>
     *
     * <code>repeated .common.ItemInfo itemInfos = 1;</code>
     */
    public java.util.List<? extends message.common.Common.ItemInfoOrBuilder> 
        getItemInfosOrBuilderList() {
      return itemInfos_;
    }
    /**
     * <pre>
     *道具信息 itemCount = 0 表示删除
     * </pre>
     *
     * <code>repeated .common.ItemInfo itemInfos = 1;</code>
     */
    public int getItemInfosCount() {
      return itemInfos_.size();
    }
    /**
     * <pre>
     *道具信息 itemCount = 0 表示删除
     * </pre>
     *
     * <code>repeated .common.ItemInfo itemInfos = 1;</code>
     */
    public message.common.Common.ItemInfo getItemInfos(int index) {
      return itemInfos_.get(index);
    }
    /**
     * <pre>
     *道具信息 itemCount = 0 表示删除
     * </pre>
     *
     * <code>repeated .common.ItemInfo itemInfos = 1;</code>
     */
    public message.common.Common.ItemInfoOrBuilder getItemInfosOrBuilder(
        int index) {
      return itemInfos_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < itemInfos_.size(); i++) {
        output.writeMessage(1, itemInfos_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < itemInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, itemInfos_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.Bag.SC_UpdateItemInfos)) {
        return super.equals(obj);
      }
      message.Bag.SC_UpdateItemInfos other = (message.Bag.SC_UpdateItemInfos) obj;

      boolean result = true;
      result = result && getItemInfosList()
          .equals(other.getItemInfosList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemInfosCount() > 0) {
        hash = (37 * hash) + ITEMINFOS_FIELD_NUMBER;
        hash = (53 * hash) + getItemInfosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.Bag.SC_UpdateItemInfos parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Bag.SC_UpdateItemInfos parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Bag.SC_UpdateItemInfos parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Bag.SC_UpdateItemInfos parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Bag.SC_UpdateItemInfos parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Bag.SC_UpdateItemInfos parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Bag.SC_UpdateItemInfos parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.Bag.SC_UpdateItemInfos parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Bag.SC_UpdateItemInfos parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static message.Bag.SC_UpdateItemInfos parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Bag.SC_UpdateItemInfos parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.Bag.SC_UpdateItemInfos parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.Bag.SC_UpdateItemInfos prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *服务器主动推送更新背包数据
     * </pre>
     *
     * Protobuf type {@code bag.SC_UpdateItemInfos}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bag.SC_UpdateItemInfos)
        message.Bag.SC_UpdateItemInfosOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.Bag.internal_static_bag_SC_UpdateItemInfos_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.Bag.internal_static_bag_SC_UpdateItemInfos_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.Bag.SC_UpdateItemInfos.class, message.Bag.SC_UpdateItemInfos.Builder.class);
      }

      // Construct using message.Bag.SC_UpdateItemInfos.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemInfosFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (itemInfosBuilder_ == null) {
          itemInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemInfosBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.Bag.internal_static_bag_SC_UpdateItemInfos_descriptor;
      }

      public message.Bag.SC_UpdateItemInfos getDefaultInstanceForType() {
        return message.Bag.SC_UpdateItemInfos.getDefaultInstance();
      }

      public message.Bag.SC_UpdateItemInfos build() {
        message.Bag.SC_UpdateItemInfos result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public message.Bag.SC_UpdateItemInfos buildPartial() {
        message.Bag.SC_UpdateItemInfos result = new message.Bag.SC_UpdateItemInfos(this);
        int from_bitField0_ = bitField0_;
        if (itemInfosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            itemInfos_ = java.util.Collections.unmodifiableList(itemInfos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.itemInfos_ = itemInfos_;
        } else {
          result.itemInfos_ = itemInfosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.Bag.SC_UpdateItemInfos) {
          return mergeFrom((message.Bag.SC_UpdateItemInfos)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.Bag.SC_UpdateItemInfos other) {
        if (other == message.Bag.SC_UpdateItemInfos.getDefaultInstance()) return this;
        if (itemInfosBuilder_ == null) {
          if (!other.itemInfos_.isEmpty()) {
            if (itemInfos_.isEmpty()) {
              itemInfos_ = other.itemInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemInfosIsMutable();
              itemInfos_.addAll(other.itemInfos_);
            }
            onChanged();
          }
        } else {
          if (!other.itemInfos_.isEmpty()) {
            if (itemInfosBuilder_.isEmpty()) {
              itemInfosBuilder_.dispose();
              itemInfosBuilder_ = null;
              itemInfos_ = other.itemInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemInfosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemInfosFieldBuilder() : null;
            } else {
              itemInfosBuilder_.addAllMessages(other.itemInfos_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        message.Bag.SC_UpdateItemInfos parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (message.Bag.SC_UpdateItemInfos) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<message.common.Common.ItemInfo> itemInfos_ =
        java.util.Collections.emptyList();
      private void ensureItemInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          itemInfos_ = new java.util.ArrayList<message.common.Common.ItemInfo>(itemInfos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          message.common.Common.ItemInfo, message.common.Common.ItemInfo.Builder, message.common.Common.ItemInfoOrBuilder> itemInfosBuilder_;

      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public java.util.List<message.common.Common.ItemInfo> getItemInfosList() {
        if (itemInfosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(itemInfos_);
        } else {
          return itemInfosBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public int getItemInfosCount() {
        if (itemInfosBuilder_ == null) {
          return itemInfos_.size();
        } else {
          return itemInfosBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public message.common.Common.ItemInfo getItemInfos(int index) {
        if (itemInfosBuilder_ == null) {
          return itemInfos_.get(index);
        } else {
          return itemInfosBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public Builder setItemInfos(
          int index, message.common.Common.ItemInfo value) {
        if (itemInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemInfosIsMutable();
          itemInfos_.set(index, value);
          onChanged();
        } else {
          itemInfosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public Builder setItemInfos(
          int index, message.common.Common.ItemInfo.Builder builderForValue) {
        if (itemInfosBuilder_ == null) {
          ensureItemInfosIsMutable();
          itemInfos_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemInfosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public Builder addItemInfos(message.common.Common.ItemInfo value) {
        if (itemInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemInfosIsMutable();
          itemInfos_.add(value);
          onChanged();
        } else {
          itemInfosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public Builder addItemInfos(
          int index, message.common.Common.ItemInfo value) {
        if (itemInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemInfosIsMutable();
          itemInfos_.add(index, value);
          onChanged();
        } else {
          itemInfosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public Builder addItemInfos(
          message.common.Common.ItemInfo.Builder builderForValue) {
        if (itemInfosBuilder_ == null) {
          ensureItemInfosIsMutable();
          itemInfos_.add(builderForValue.build());
          onChanged();
        } else {
          itemInfosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public Builder addItemInfos(
          int index, message.common.Common.ItemInfo.Builder builderForValue) {
        if (itemInfosBuilder_ == null) {
          ensureItemInfosIsMutable();
          itemInfos_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemInfosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public Builder addAllItemInfos(
          java.lang.Iterable<? extends message.common.Common.ItemInfo> values) {
        if (itemInfosBuilder_ == null) {
          ensureItemInfosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, itemInfos_);
          onChanged();
        } else {
          itemInfosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public Builder clearItemInfos() {
        if (itemInfosBuilder_ == null) {
          itemInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemInfosBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public Builder removeItemInfos(int index) {
        if (itemInfosBuilder_ == null) {
          ensureItemInfosIsMutable();
          itemInfos_.remove(index);
          onChanged();
        } else {
          itemInfosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public message.common.Common.ItemInfo.Builder getItemInfosBuilder(
          int index) {
        return getItemInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public message.common.Common.ItemInfoOrBuilder getItemInfosOrBuilder(
          int index) {
        if (itemInfosBuilder_ == null) {
          return itemInfos_.get(index);  } else {
          return itemInfosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public java.util.List<? extends message.common.Common.ItemInfoOrBuilder> 
           getItemInfosOrBuilderList() {
        if (itemInfosBuilder_ != null) {
          return itemInfosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(itemInfos_);
        }
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public message.common.Common.ItemInfo.Builder addItemInfosBuilder() {
        return getItemInfosFieldBuilder().addBuilder(
            message.common.Common.ItemInfo.getDefaultInstance());
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public message.common.Common.ItemInfo.Builder addItemInfosBuilder(
          int index) {
        return getItemInfosFieldBuilder().addBuilder(
            index, message.common.Common.ItemInfo.getDefaultInstance());
      }
      /**
       * <pre>
       *道具信息 itemCount = 0 表示删除
       * </pre>
       *
       * <code>repeated .common.ItemInfo itemInfos = 1;</code>
       */
      public java.util.List<message.common.Common.ItemInfo.Builder> 
           getItemInfosBuilderList() {
        return getItemInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          message.common.Common.ItemInfo, message.common.Common.ItemInfo.Builder, message.common.Common.ItemInfoOrBuilder> 
          getItemInfosFieldBuilder() {
        if (itemInfosBuilder_ == null) {
          itemInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              message.common.Common.ItemInfo, message.common.Common.ItemInfo.Builder, message.common.Common.ItemInfoOrBuilder>(
                  itemInfos_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          itemInfos_ = null;
        }
        return itemInfosBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bag.SC_UpdateItemInfos)
    }

    // @@protoc_insertion_point(class_scope:bag.SC_UpdateItemInfos)
    private static final message.Bag.SC_UpdateItemInfos DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.Bag.SC_UpdateItemInfos();
    }

    public static message.Bag.SC_UpdateItemInfos getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SC_UpdateItemInfos>
        PARSER = new com.google.protobuf.AbstractParser<SC_UpdateItemInfos>() {
      public SC_UpdateItemInfos parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SC_UpdateItemInfos(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SC_UpdateItemInfos> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SC_UpdateItemInfos> getParserForType() {
      return PARSER;
    }

    public message.Bag.SC_UpdateItemInfos getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CS_MergeItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bag.CS_MergeItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *合成的目标配置Id
     * </pre>
     *
     * <code>int32 itemId = 1;</code>
     */
    int getItemId();
  }
  /**
   * <pre>
   *合成请求
   * </pre>
   *
   * Protobuf type {@code bag.CS_MergeItem}
   */
  public  static final class CS_MergeItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bag.CS_MergeItem)
      CS_MergeItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CS_MergeItem.newBuilder() to construct.
    private CS_MergeItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CS_MergeItem() {
      itemId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CS_MergeItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              itemId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.Bag.internal_static_bag_CS_MergeItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.Bag.internal_static_bag_CS_MergeItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.Bag.CS_MergeItem.class, message.Bag.CS_MergeItem.Builder.class);
    }

    public static final int ITEMID_FIELD_NUMBER = 1;
    private int itemId_;
    /**
     * <pre>
     *合成的目标配置Id
     * </pre>
     *
     * <code>int32 itemId = 1;</code>
     */
    public int getItemId() {
      return itemId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (itemId_ != 0) {
        output.writeInt32(1, itemId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (itemId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, itemId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.Bag.CS_MergeItem)) {
        return super.equals(obj);
      }
      message.Bag.CS_MergeItem other = (message.Bag.CS_MergeItem) obj;

      boolean result = true;
      result = result && (getItemId()
          == other.getItemId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ITEMID_FIELD_NUMBER;
      hash = (53 * hash) + getItemId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.Bag.CS_MergeItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Bag.CS_MergeItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Bag.CS_MergeItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Bag.CS_MergeItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Bag.CS_MergeItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Bag.CS_MergeItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Bag.CS_MergeItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.Bag.CS_MergeItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Bag.CS_MergeItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static message.Bag.CS_MergeItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Bag.CS_MergeItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.Bag.CS_MergeItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.Bag.CS_MergeItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *合成请求
     * </pre>
     *
     * Protobuf type {@code bag.CS_MergeItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bag.CS_MergeItem)
        message.Bag.CS_MergeItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.Bag.internal_static_bag_CS_MergeItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.Bag.internal_static_bag_CS_MergeItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.Bag.CS_MergeItem.class, message.Bag.CS_MergeItem.Builder.class);
      }

      // Construct using message.Bag.CS_MergeItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        itemId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.Bag.internal_static_bag_CS_MergeItem_descriptor;
      }

      public message.Bag.CS_MergeItem getDefaultInstanceForType() {
        return message.Bag.CS_MergeItem.getDefaultInstance();
      }

      public message.Bag.CS_MergeItem build() {
        message.Bag.CS_MergeItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public message.Bag.CS_MergeItem buildPartial() {
        message.Bag.CS_MergeItem result = new message.Bag.CS_MergeItem(this);
        result.itemId_ = itemId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.Bag.CS_MergeItem) {
          return mergeFrom((message.Bag.CS_MergeItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.Bag.CS_MergeItem other) {
        if (other == message.Bag.CS_MergeItem.getDefaultInstance()) return this;
        if (other.getItemId() != 0) {
          setItemId(other.getItemId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        message.Bag.CS_MergeItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (message.Bag.CS_MergeItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int itemId_ ;
      /**
       * <pre>
       *合成的目标配置Id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       */
      public int getItemId() {
        return itemId_;
      }
      /**
       * <pre>
       *合成的目标配置Id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       */
      public Builder setItemId(int value) {
        
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *合成的目标配置Id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       */
      public Builder clearItemId() {
        
        itemId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bag.CS_MergeItem)
    }

    // @@protoc_insertion_point(class_scope:bag.CS_MergeItem)
    private static final message.Bag.CS_MergeItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.Bag.CS_MergeItem();
    }

    public static message.Bag.CS_MergeItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CS_MergeItem>
        PARSER = new com.google.protobuf.AbstractParser<CS_MergeItem>() {
      public CS_MergeItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CS_MergeItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CS_MergeItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CS_MergeItem> getParserForType() {
      return PARSER;
    }

    public message.Bag.CS_MergeItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SC_MergeItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bag.SC_MergeItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *合成的目标配置Id
     * </pre>
     *
     * <code>int32 itemId = 1;</code>
     */
    int getItemId();
  }
  /**
   * <pre>
   *合成返回
   * </pre>
   *
   * Protobuf type {@code bag.SC_MergeItem}
   */
  public  static final class SC_MergeItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bag.SC_MergeItem)
      SC_MergeItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SC_MergeItem.newBuilder() to construct.
    private SC_MergeItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SC_MergeItem() {
      itemId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SC_MergeItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              itemId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.Bag.internal_static_bag_SC_MergeItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.Bag.internal_static_bag_SC_MergeItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.Bag.SC_MergeItem.class, message.Bag.SC_MergeItem.Builder.class);
    }

    public static final int ITEMID_FIELD_NUMBER = 1;
    private int itemId_;
    /**
     * <pre>
     *合成的目标配置Id
     * </pre>
     *
     * <code>int32 itemId = 1;</code>
     */
    public int getItemId() {
      return itemId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (itemId_ != 0) {
        output.writeInt32(1, itemId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (itemId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, itemId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.Bag.SC_MergeItem)) {
        return super.equals(obj);
      }
      message.Bag.SC_MergeItem other = (message.Bag.SC_MergeItem) obj;

      boolean result = true;
      result = result && (getItemId()
          == other.getItemId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ITEMID_FIELD_NUMBER;
      hash = (53 * hash) + getItemId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.Bag.SC_MergeItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Bag.SC_MergeItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Bag.SC_MergeItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Bag.SC_MergeItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Bag.SC_MergeItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Bag.SC_MergeItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Bag.SC_MergeItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.Bag.SC_MergeItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Bag.SC_MergeItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static message.Bag.SC_MergeItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Bag.SC_MergeItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.Bag.SC_MergeItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.Bag.SC_MergeItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *合成返回
     * </pre>
     *
     * Protobuf type {@code bag.SC_MergeItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bag.SC_MergeItem)
        message.Bag.SC_MergeItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.Bag.internal_static_bag_SC_MergeItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.Bag.internal_static_bag_SC_MergeItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.Bag.SC_MergeItem.class, message.Bag.SC_MergeItem.Builder.class);
      }

      // Construct using message.Bag.SC_MergeItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        itemId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.Bag.internal_static_bag_SC_MergeItem_descriptor;
      }

      public message.Bag.SC_MergeItem getDefaultInstanceForType() {
        return message.Bag.SC_MergeItem.getDefaultInstance();
      }

      public message.Bag.SC_MergeItem build() {
        message.Bag.SC_MergeItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public message.Bag.SC_MergeItem buildPartial() {
        message.Bag.SC_MergeItem result = new message.Bag.SC_MergeItem(this);
        result.itemId_ = itemId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.Bag.SC_MergeItem) {
          return mergeFrom((message.Bag.SC_MergeItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.Bag.SC_MergeItem other) {
        if (other == message.Bag.SC_MergeItem.getDefaultInstance()) return this;
        if (other.getItemId() != 0) {
          setItemId(other.getItemId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        message.Bag.SC_MergeItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (message.Bag.SC_MergeItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int itemId_ ;
      /**
       * <pre>
       *合成的目标配置Id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       */
      public int getItemId() {
        return itemId_;
      }
      /**
       * <pre>
       *合成的目标配置Id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       */
      public Builder setItemId(int value) {
        
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *合成的目标配置Id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       */
      public Builder clearItemId() {
        
        itemId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bag.SC_MergeItem)
    }

    // @@protoc_insertion_point(class_scope:bag.SC_MergeItem)
    private static final message.Bag.SC_MergeItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.Bag.SC_MergeItem();
    }

    public static message.Bag.SC_MergeItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SC_MergeItem>
        PARSER = new com.google.protobuf.AbstractParser<SC_MergeItem>() {
      public SC_MergeItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SC_MergeItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SC_MergeItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SC_MergeItem> getParserForType() {
      return PARSER;
    }

    public message.Bag.SC_MergeItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CS_CreateItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bag.CS_CreateItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *目标配置Id
     * </pre>
     *
     * <code>int32 itemId = 1;</code>
     */
    int getItemId();
  }
  /**
   * <pre>
   *研发请求
   * </pre>
   *
   * Protobuf type {@code bag.CS_CreateItem}
   */
  public  static final class CS_CreateItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bag.CS_CreateItem)
      CS_CreateItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CS_CreateItem.newBuilder() to construct.
    private CS_CreateItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CS_CreateItem() {
      itemId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CS_CreateItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              itemId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.Bag.internal_static_bag_CS_CreateItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.Bag.internal_static_bag_CS_CreateItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.Bag.CS_CreateItem.class, message.Bag.CS_CreateItem.Builder.class);
    }

    public static final int ITEMID_FIELD_NUMBER = 1;
    private int itemId_;
    /**
     * <pre>
     *目标配置Id
     * </pre>
     *
     * <code>int32 itemId = 1;</code>
     */
    public int getItemId() {
      return itemId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (itemId_ != 0) {
        output.writeInt32(1, itemId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (itemId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, itemId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.Bag.CS_CreateItem)) {
        return super.equals(obj);
      }
      message.Bag.CS_CreateItem other = (message.Bag.CS_CreateItem) obj;

      boolean result = true;
      result = result && (getItemId()
          == other.getItemId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ITEMID_FIELD_NUMBER;
      hash = (53 * hash) + getItemId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.Bag.CS_CreateItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Bag.CS_CreateItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Bag.CS_CreateItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Bag.CS_CreateItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Bag.CS_CreateItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Bag.CS_CreateItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Bag.CS_CreateItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.Bag.CS_CreateItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Bag.CS_CreateItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static message.Bag.CS_CreateItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Bag.CS_CreateItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.Bag.CS_CreateItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.Bag.CS_CreateItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *研发请求
     * </pre>
     *
     * Protobuf type {@code bag.CS_CreateItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bag.CS_CreateItem)
        message.Bag.CS_CreateItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.Bag.internal_static_bag_CS_CreateItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.Bag.internal_static_bag_CS_CreateItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.Bag.CS_CreateItem.class, message.Bag.CS_CreateItem.Builder.class);
      }

      // Construct using message.Bag.CS_CreateItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        itemId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.Bag.internal_static_bag_CS_CreateItem_descriptor;
      }

      public message.Bag.CS_CreateItem getDefaultInstanceForType() {
        return message.Bag.CS_CreateItem.getDefaultInstance();
      }

      public message.Bag.CS_CreateItem build() {
        message.Bag.CS_CreateItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public message.Bag.CS_CreateItem buildPartial() {
        message.Bag.CS_CreateItem result = new message.Bag.CS_CreateItem(this);
        result.itemId_ = itemId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.Bag.CS_CreateItem) {
          return mergeFrom((message.Bag.CS_CreateItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.Bag.CS_CreateItem other) {
        if (other == message.Bag.CS_CreateItem.getDefaultInstance()) return this;
        if (other.getItemId() != 0) {
          setItemId(other.getItemId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        message.Bag.CS_CreateItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (message.Bag.CS_CreateItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int itemId_ ;
      /**
       * <pre>
       *目标配置Id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       */
      public int getItemId() {
        return itemId_;
      }
      /**
       * <pre>
       *目标配置Id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       */
      public Builder setItemId(int value) {
        
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标配置Id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       */
      public Builder clearItemId() {
        
        itemId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bag.CS_CreateItem)
    }

    // @@protoc_insertion_point(class_scope:bag.CS_CreateItem)
    private static final message.Bag.CS_CreateItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.Bag.CS_CreateItem();
    }

    public static message.Bag.CS_CreateItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CS_CreateItem>
        PARSER = new com.google.protobuf.AbstractParser<CS_CreateItem>() {
      public CS_CreateItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CS_CreateItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CS_CreateItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CS_CreateItem> getParserForType() {
      return PARSER;
    }

    public message.Bag.CS_CreateItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SC_CreateItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bag.SC_CreateItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *目标配置Id
     * </pre>
     *
     * <code>int32 itemId = 1;</code>
     */
    int getItemId();
  }
  /**
   * <pre>
   *研发返回
   * </pre>
   *
   * Protobuf type {@code bag.SC_CreateItem}
   */
  public  static final class SC_CreateItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bag.SC_CreateItem)
      SC_CreateItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SC_CreateItem.newBuilder() to construct.
    private SC_CreateItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SC_CreateItem() {
      itemId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SC_CreateItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              itemId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.Bag.internal_static_bag_SC_CreateItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.Bag.internal_static_bag_SC_CreateItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.Bag.SC_CreateItem.class, message.Bag.SC_CreateItem.Builder.class);
    }

    public static final int ITEMID_FIELD_NUMBER = 1;
    private int itemId_;
    /**
     * <pre>
     *目标配置Id
     * </pre>
     *
     * <code>int32 itemId = 1;</code>
     */
    public int getItemId() {
      return itemId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (itemId_ != 0) {
        output.writeInt32(1, itemId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (itemId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, itemId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.Bag.SC_CreateItem)) {
        return super.equals(obj);
      }
      message.Bag.SC_CreateItem other = (message.Bag.SC_CreateItem) obj;

      boolean result = true;
      result = result && (getItemId()
          == other.getItemId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ITEMID_FIELD_NUMBER;
      hash = (53 * hash) + getItemId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.Bag.SC_CreateItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Bag.SC_CreateItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Bag.SC_CreateItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Bag.SC_CreateItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Bag.SC_CreateItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Bag.SC_CreateItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Bag.SC_CreateItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.Bag.SC_CreateItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Bag.SC_CreateItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static message.Bag.SC_CreateItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Bag.SC_CreateItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static message.Bag.SC_CreateItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.Bag.SC_CreateItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *研发返回
     * </pre>
     *
     * Protobuf type {@code bag.SC_CreateItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bag.SC_CreateItem)
        message.Bag.SC_CreateItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.Bag.internal_static_bag_SC_CreateItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.Bag.internal_static_bag_SC_CreateItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.Bag.SC_CreateItem.class, message.Bag.SC_CreateItem.Builder.class);
      }

      // Construct using message.Bag.SC_CreateItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        itemId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.Bag.internal_static_bag_SC_CreateItem_descriptor;
      }

      public message.Bag.SC_CreateItem getDefaultInstanceForType() {
        return message.Bag.SC_CreateItem.getDefaultInstance();
      }

      public message.Bag.SC_CreateItem build() {
        message.Bag.SC_CreateItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public message.Bag.SC_CreateItem buildPartial() {
        message.Bag.SC_CreateItem result = new message.Bag.SC_CreateItem(this);
        result.itemId_ = itemId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.Bag.SC_CreateItem) {
          return mergeFrom((message.Bag.SC_CreateItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.Bag.SC_CreateItem other) {
        if (other == message.Bag.SC_CreateItem.getDefaultInstance()) return this;
        if (other.getItemId() != 0) {
          setItemId(other.getItemId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        message.Bag.SC_CreateItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (message.Bag.SC_CreateItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int itemId_ ;
      /**
       * <pre>
       *目标配置Id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       */
      public int getItemId() {
        return itemId_;
      }
      /**
       * <pre>
       *目标配置Id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       */
      public Builder setItemId(int value) {
        
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标配置Id
       * </pre>
       *
       * <code>int32 itemId = 1;</code>
       */
      public Builder clearItemId() {
        
        itemId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bag.SC_CreateItem)
    }

    // @@protoc_insertion_point(class_scope:bag.SC_CreateItem)
    private static final message.Bag.SC_CreateItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.Bag.SC_CreateItem();
    }

    public static message.Bag.SC_CreateItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SC_CreateItem>
        PARSER = new com.google.protobuf.AbstractParser<SC_CreateItem>() {
      public SC_CreateItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SC_CreateItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SC_CreateItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SC_CreateItem> getParserForType() {
      return PARSER;
    }

    public message.Bag.SC_CreateItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bag_SC_UpdateItemInfos_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bag_SC_UpdateItemInfos_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bag_CS_MergeItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bag_CS_MergeItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bag_SC_MergeItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bag_SC_MergeItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bag_CS_CreateItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bag_CS_CreateItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bag_SC_CreateItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bag_SC_CreateItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tbag.proto\022\003bag\032\023common/common.proto\"9\n" +
      "\022SC_UpdateItemInfos\022#\n\titemInfos\030\001 \003(\0132\020" +
      ".common.ItemInfo\"\036\n\014CS_MergeItem\022\016\n\006item" +
      "Id\030\001 \001(\005\"\036\n\014SC_MergeItem\022\016\n\006itemId\030\001 \001(\005" +
      "\"\037\n\rCS_CreateItem\022\016\n\006itemId\030\001 \001(\005\"\037\n\rSC_" +
      "CreateItem\022\016\n\006itemId\030\001 \001(\005B\016\n\007messageB\003B" +
      "agb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          message.common.Common.getDescriptor(),
        }, assigner);
    internal_static_bag_SC_UpdateItemInfos_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bag_SC_UpdateItemInfos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bag_SC_UpdateItemInfos_descriptor,
        new java.lang.String[] { "ItemInfos", });
    internal_static_bag_CS_MergeItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bag_CS_MergeItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bag_CS_MergeItem_descriptor,
        new java.lang.String[] { "ItemId", });
    internal_static_bag_SC_MergeItem_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bag_SC_MergeItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bag_SC_MergeItem_descriptor,
        new java.lang.String[] { "ItemId", });
    internal_static_bag_CS_CreateItem_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_bag_CS_CreateItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bag_CS_CreateItem_descriptor,
        new java.lang.String[] { "ItemId", });
    internal_static_bag_SC_CreateItem_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_bag_SC_CreateItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bag_SC_CreateItem_descriptor,
        new java.lang.String[] { "ItemId", });
    message.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
